[package]
name = "function"
version = "0.1.0"
edition = "2021"

[dependencies]
httpcodec = "0.2.3"
bytecodec = "0.4.15"
wasmedge_wasi_socket = "0.4.2"
log = "0.4.0"

[dev-dependencies]
http_req_wasi  = "0.10"
